### ISSUE TITLE
How does it work? and some question about ipchanger

### ISSUE THREAD

**Issue by chrisovato** [seevik2580/tor-ip-changer#11]
Hi, 
can you explain how this ipchanger work? 
How is it possible that it overrides the ip router?

**Comment by seevik2580** [comment]
sure, a little theory for start...
Tor ipchanger does not override router ip, it just create proxy which is connected inside TOR network which you can use to hide your real ip address, and you can change that proxy IP inside TOR network every X. then you have to decide which apps will use this proxy to be anonymized. For most cases its just for browsers, but you can use it for every app which support socks4/5 type proxy, and also you can use third party software to anonymize other apps, not just browsers, even whole computer with software like Proxifier.

example of usage:
- just start ipchanger.exe
- at the top select TOR server > Start
- wait until `TOR server started` 
- at the top select IP changer > Start
- then in your browser set proxy type Socks with ip 127.0.0.1 and port 9050
- then go to http://checkip.amazonaws.com/ or http://showip.net/ or whenever it shows you IP, and after next period (default 10 seconds) refresh page and if it works, you will always see different IP

**Comment by seevik2580** [comment]
Hello,
TOR IP Changer does not override router ip, it just create proxy which is connected inside TOR network which you can use to hide your real ip address for browser or apps that supports socks4/5 type proxy, and you can change that IP inside TOR network every X seconds. For most cases its just for browsers, but you can use third party software to co-operate with TOR IP Changer to anonymize not just browsers but also other apps which does not have support for socks4/5 type proxy or even whole computer with software like Proxifier.

example of usage:
- just start ipchanger.exe
- at the top select TOR server > Start
- wait until `TOR server started` 
- at the top select IP changer > Start
- then in your browser set proxy type Socks with ip 127.0.0.1 and port 9050
- then go to http://checkip.amazonaws.com/ or http://showip.net/ or whenever it shows you IP, and after next period (default 10 seconds) refresh page and if it works, you will always see different IP

**Comment by seevik2580** [comment]
Hello,
TOR IP Changer does not override router ip, it just create proxy which is connected inside TOR network which you can use to hide your real ip address for browser or apps that supports socks4/5 type proxy, and you can change that IP inside TOR network every X seconds. For most cases its just for browsers, but you can use third party software to co-operate with TOR IP Changer to anonymize not just browsers but also other apps which does not have support for socks4/5 type proxy or even whole computer with software like Proxifier.

example of usage:
- just start ipchanger.exe
- at the top select TOR server > Start
- wait until `TOR server started` 
- at the top select IP changer > Start
- then in your browser set proxy type Socks with ip 127.0.0.1 and port 9050
- then go to http://checkip.amazonaws.com/ or http://showip.net/ or whenever it shows you IP, and after next period (default 10 seconds) refresh page and if it works, you will always see different IP

you can also use multiple proxy with option `-m number`
example:

you have two browsers and you want to have different IP for both of them
- use `ipchanger.exe -m 2`
- at the top select TOR server > Start
- wait until `TOR server started` 
- at the top select IP changer > Start
- in your first browser set proxy type Socks with ip 127.0.0.1 and port 9050
- in your second browser set proxy type Socks with ip 127.0.0.1 and port 9051
- then go to http://checkip.amazonaws.com/ or http://showip.net/ or whenever it shows you IP, and after next period (default 10 seconds) refresh page and if it works, you will always see different IP for both browsers at the same time

you can use up to 100 different proxies :)

also there is a API for IP Changer remote control, but thats a little harder to use. 
example:

you have browser with automation extension like iMacros and you want to change IP only when you do specific operation, like poll voting ... then you can connect to API on port 14999 and call it with with every programming language that supports Socks4/5 type proxy... python,php,c++,c#, java, etc ...

`create index.php`

```
<?
      $host = "localhost";
      $port = "14999";
      $timeout = "5";
      $f=fsockopen($host,$port,$timeout);
      if (!$f) {
              echo "not connected";
      } else {
              echo "connected<br>";

              echo fgets($f, 1024);
              fwrite($f,"tor start\r\n");
              sleep(30);
              fwrite($f,"interval 30\r\n");
              sleep(1);
              fwrite($f,"changeip start\r\n");
              sleep(1);
              fwrite($f,"exit\r\n");
              echo fgets($f, 1024);
               fclose($f);
      }
?>
```
and inside your iMacros define that index.php page to be called after your wanted operation.

**Comment by seevik2580** [comment]
Hello,
TOR IP Changer does not override router ip, it just create proxy which is connected inside TOR network which you can use to hide your real ip address for browser or apps that supports socks4/5 type proxy, and you can change that IP inside TOR network every X seconds. For most cases its just for browsers, but you can use third party software to co-operate with TOR IP Changer to anonymize not just browsers but also other apps which does not have support for socks4/5 type proxy or even whole computer with software like Proxifier.

example of usage:
- just start ipchanger.exe
- at the top select TOR server > Start
- wait until `TOR server started` 
- at the top select IP changer > Start
- then in your browser set proxy type Socks with ip 127.0.0.1 and port 9050
- then go to http://checkip.amazonaws.com/ or http://showip.net/ or whenever it shows you IP, and after next period (default 10 seconds) refresh page and if it works, you will always see different IP

you can also use multiple proxy with option `-m number`
example:

you have two browsers and you want to have different IP for both of them
- use `ipchanger.exe -m 2`
- at the top select TOR server > Start
- wait until `TOR server started` 
- at the top select IP changer > Start
- in your first browser set proxy type Socks with ip 127.0.0.1 and port 9050
- in your second browser set proxy type Socks with ip 127.0.0.1 and port 9051
- then go to http://checkip.amazonaws.com/ or http://showip.net/ or whenever it shows you IP, and after next period (default 10 seconds) refresh page and if it works, you will always see different IP for both browsers at the same time

you can use up to 100 different proxies :)

also there is a API for IP Changer remote control, but thats a little harder to use. 
lets say you have browser with automation extension like iMacros and you want to change IP only when you do specific operation, like poll voting ... then you can connect to API on port 14999 and call it with with every programming language that supports Socks4/5 type proxy... python,php,c++,c#, java, etc ...
- example php
`create index.php`

```
<?
      $host = "localhost";
      $port = "14999";
      $timeout = "5";
      $f=fsockopen($host,$port,$timeout);
      if (!$f) {
              echo "not connected";
      } else {
              echo "connected<br>";

              echo fgets($f, 1024);
              fwrite($f,"tor start\r\n");
              sleep(30);
              fwrite($f,"interval 30\r\n");
              sleep(1);
              fwrite($f,"changeip start\r\n");
              sleep(1);
              fwrite($f,"exit\r\n");
              echo fgets($f, 1024);
               fclose($f);
      }
?>
```
and inside your iMacros define that index.php page to be called after your wanted operation.

**Comment by chrisovato** [comment]
I have already implemented it with my python app  
But I want to know how your it is changing IP because it is a very rare application and I am seeing the first-time app like this 💯  

You wrote that I can use 100 proxies to its mean that 100 ports are available for changing ip and are available for the internet transfer?
Where are these proxies hosted? Is it for free?
How many ip address are available in your app?

**Comment by seevik2580** [comment]
please look here how TOR network works. https://en.wikipedia.org/wiki/Tor_(anonymity_network)
and let me explain one thing... i am not developer or maintainer TOR network, i am just ordinary user like you and i just used existed network (TOR) and existed mechanism inside this network to achieve this.
yes its totaly **FREE**, no money needed and as long as TOR network will be **FREE** to use
you can use up to 100 proxies with `ipchanger -m 100` and it will bind 100 ports in your PC from 9050 ending to 9150. and every proxy **should** have different IP and will be available for internet trasfer. i cannot add more IPs inside TOR network neither you just like that because they are called **EXIT NODES** and if somebody create new **EXIT NODE**, it can be used inside TOR network. So there are thousands of them hosted across the whole world and you can use them to anonymize your real IP. so if you want to add some new IPs, you have to create your own **EXIT NODE**, look at https://tor-relay.co/ it will helps you to generate config to achieve that.
some exit nodes are good, some of them are bad. it depends on individual how he will maintain this specific node.

**Comment by chrisovato** [comment]
Awesome, few more question: 

People, who host their machines are earning some money? Or they are doing it for 100% free?  
Why only 100 proxies? It is your choice, can it be bigger?
Where I can see relays which I can use to connect to them and use their ip's?
How many ip address are available in the Tor? Will they repeat, if yes when?

My laptop every X seconds connects via proxy to the relays and this relay shares his IP and I use it? Am I correct?

**Comment by seevik2580** [comment]
- i dont think so, and if they earning some money, its up to them, not up to me, i just wrote app which can control identity in tor network. i personally dont host any of tor relays or nodes and i dont want any money for this app :)
- because it will launch 100x tor.exe process so if you have slow computer it can totally freeze your system, thats why only 100. its open-sourced now, so you can fork this project and increase the limitations for yourself and recompile to new exe file.
- google.com, you have to search by youself. there are several sites which can show TOR existing relays
- thousands, i dont know exact number, and yes they will repeat, its purely random with no selection mechanism based, so it could be in next two minutes or in next two months. you can set specific country if you want to prevent other IPs from other countries be used.
- correct

**Comment by chrisovato** [comment]
So we can connect to about 6000 relays, based on this https://metrics.torproject.org/networksize.html. Is it correct?
I have found [relay](https://metrics.torproject.org/rs.html#details/42B4F52C5B11E4D39855F654955425B0D5A0598B) how I can use his ip? I mean how can I connect to it?

**Comment by seevik2580** [comment]
you cant use targeted connection method to specific relay with tor ip changer, only random selection.

**Comment by chrisovato** [comment]
Your app from where is taking relays? Is it some kind of API or what?

**Comment by seevik2580** [comment]
yes, TOR has its own API for control with telnet, so i can give him command to request new identity. my app doesnt know any of relay list or so.
if you run `tor.exe --ControlPort number` then you can telnet that port and control tor by yourself. which my app does for you.

**Comment by chrisovato** [comment]
tor.exe you mean browser which I can download from [here](https://www.torproject.org/download/) ?
Have you used [stem ](https://stem.torproject.org/index.html) in your app?

**Comment by seevik2580** [comment]
nope, browser has tor.exe build in. 
you need just tor.exe, you can download it from https://www.torproject.org/download/tor/ and look for Windows Expert Bundle, download zip and there will be tor.exe which is only console/terminal utility - no GUI

**Comment by chrisovato** [comment]
Have you used stem in your app?
What this line do ```tn = telnetlib.Telnet('127.0.0.1', '14999', 5)```?

**Comment by seevik2580** [comment]
no i dont use stem, just pure telnet.
port 14999 is for API to control TOR IP Changer not TOR

**Comment by chrisovato** [comment]
What is the command to tor to look for a new relay? I am here: [link](https://github.com/seevik2580/tor-ip-changer/blob/b47ead60d044299ce42cf52a50adb310e0aebadc/source-code-win/1.2.3/start.pyw#L1155)

When I am connecting through a proxy(relay), does this relay see my data, or it is encrypted? 
Could you explain why I am connecting to my self in a browser setting proxy? I set host SOCKS to 127.0.0.1 and port to 9050, why? Shouldn't I connect to one of the relay?

**Comment by seevik2580** [comment]
s.send(("signal NEWNYM").encode('ascii') + b"\r\n")

sure they can see your traffic, thats why i told you "some exit nodes are good, some of them are bad. it depends on individual how he will maintain this specific node.", try to use Bridges, its in settings on the top menu, then you wont be connected to TOR network directly but through somewhereelse so its hard to track your location if you are worried.

you connecting to yourself because its easier to configure it like that. if its not this way then you have to change proxy for every relay for yourself and with big list that could be very annoying. so you just connect to TOR on localhost and TOR will take care of the rest for you ... he connect you to specific relay and also make a tunnel for you... 

if you have more question about TOR itself, please look here https://en.wikipedia.org/wiki/Tor_(anonymity_network)
i dont know everything about it.

**Comment by seevik2580** [comment]
[Here](https://github.com/seevik2580/tor-ip-changer/blob/b47ead60d044299ce42cf52a50adb310e0aebadc/source-code-win/1.2.3/start.pyw#L1185)

relays cant see your traffic but exit node can. thats why i told you "some exit nodes are good, some of them are bad. it depends on individual how he will maintain this specific node.", try to use Bridges, its in settings on the top menu, then you wont be connected to TOR network directly but through somewhereelse so its hard to track your location if you are worried.

you connecting to yourself because its easier to configure it like that. if its not this way then you have to change proxy for every relay for yourself and with big list that could be very annoying. so you just connect to TOR on localhost and TOR will take care of the rest for you ... he connect you to specific relay and also make a tunnel for you... 

if you have more question about TOR itself, please look here https://en.wikipedia.org/wiki/Tor_(anonymity_network)
i dont know everything about it.

**Comment by chrisovato** [comment]
So if I type this ```signal NEWNYM``` in cmd, will I connect to new relay? 
What else can I type for to tor CLI?

**Comment by seevik2580** [comment]
- yes but you need to be connected by telnet to controlport first
- you have to google for yourself to find all commands
:)

**Comment by chrisovato** [comment]
What is the IP and port to connect by telnet to tor?

**Comment by seevik2580** [comment]
lol i already told you. do you even know how to use telnet ? :D please ask questions about tor ipchanger not about tor itself or i close this issue. thank you
telnet to 127.0.0.1 and port is what you set in `tor.exe --ControlPort number` like `tor.exe --ControlPort 10500`
then telnet 127.0.0.1 port 10500

**Comment by chrisovato** [comment]
I am trying to understand whats going on in this [file](https://github.com/seevik2580/tor-ip-changer/blob/b47ead60d044299ce42cf52a50adb310e0aebadc/source-code-win/1.2.3/start.pyw) 

I am trying to search on web about telnet and tor commands like ```signal NEWNYM && GETINFO``` and I cannot find. Could you send a link to documentation where is written about these commands?

**Comment by seevik2580** [comment]
i do not have any documentation for TOR, just google. its not easy to find but its on the internet, try to search other projects.

whats going on in that file is pretty simple.. its just start tor.exe with some arguments and custom control port, then it will connect by telnet to that control port and it starts sending command to request new identity every X seconds, it also closes previous connected circuits to prevent them stay connected after you change relay. it also let you select specific country or use bridges. nothing more

**Comment by chrisovato** [comment]
I could not find :(
could you link some page, where is written how to check delay ms, ip etc?

**Comment by seevik2580** [comment]
i use my own methods to achieve this
[ip check](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/start.pyw#L966)
[delay ms](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/start.pyw#L982)

**Comment by chrisovato** [comment]
1) Why if I telnet ```tn.write(b"help\r\n")``` I do not get response? 
2) Could you explain what [these arguments](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/start.pyw#L701) do? 
3) Why you have written all code in one class? 
4) What type of module I can exclude [here](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/setup-ipchanger.py#L16)?
5) Why do I not see tor.exe in your repo? How it works that, it is not there but your app is working?

**Comment by chrisovato** [comment]
1) Why if I telnet ```tn.write(b"help\r\n")``` I do not get response? 
2) Could you explain what [these arguments](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/start.pyw#L701) do? 
4) What type of module I can exclude [here](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/setup-ipchanger.py#L16)?
5) Why do I not see tor.exe in your repo? How it works that, it is not there but your app is working?

**Comment by seevik2580** [comment]
1. its simple .. because you just send commands without expecting output response, if you want to see response you have to read it with telnetlib methods, please learn how telnetlib works [Here](http://www.cc.kyoto-su.ac.jp/~atsushi/Programs/VisualWorks/CSV2HTML/CSV2HTML_PyDoc/telnetlib.html) or [Here](https://docs.python.org/3/library/telnetlib.html)

example:

```
#import telnetlib and time
  import telnetlib, time
#connect to localhost
  tn = telnetlib.Telnet('127.0.0.1', '14999', 5)
#send some commands
  tn.write(b"help\r\n")
  tn.write(b"exit\r\n")
#wait for response
  time.sleep(1)
#read response
  print(tn.read_very_eager().decode('ascii'))
```
![image](https://user-images.githubusercontent.com/22060747/87017088-d4c08800-c1cf-11ea-8cdc-4c617ec12fbc.png)

2. i dont understand this question if you linked answer :D
3. none
4. its in repo, you have to look better .. [Here](https://github.com/seevik2580/tor-ip-changer/tree/master/tor)

**Comment by chrisovato** [comment]
Could you explain how [that](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/start.pyw#L1137) function works? 
What [that ](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/start.pyw#L1155 )line, that [line ](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/start.pyw#L1156) and that [line ](https://github.com/seevik2580/tor-ip-changer/blob/ca6cf093f7e18bb260eb219e10886117ce5ec047/source-code-win/1.2.3/start.pyw#L1185)do?

**Comment by seevik2580** [comment]
- ok function in a nutshell = it sends command to tor through telnet to request new relay and also close all previous connected circuits. it works like this .. it connects to control port, then it sends password to be allowed to control tor.exe with telnet, then it asks for info of all connected circuits and their IDs, then close all of them based by IDs and then it requests new identity in tor network
- first mentioned line is just authentication method which is needed for to be allowed use tor.exe with telnet because i used `--HashedControlPassword "myHashedPassword" --ControlPort number` and that means you have opened controlport but only with authentication method and not for everyone who just telnet controlport. its for security purposes so nobody else can telnet yours controlport.
if you want to create authentication method for yourself you have to run `tor.exe --hash-password "my_password"` in terminal and this will generate hash for you, then use that hash with `tor.exe --HashedControlPassword "yourHash" --ControlPort <number>` and then you have to send that password through telnet to tor.exe everytime you connect your controlport... passwords through telnet are sended in plaintext.
- second mentioned line is for get all info about all connected circuits and their IDs
- third mentioned line is for asking tor for new identity = new IP = new relay = new circuits

**Comment by seevik2580** [comment]
btw the question about HashedControlPassword also gave me an idea how to generate different random hashes compatible with tor.exe for every single instance and not just same one for every tor.exe. thanks, i will set it soon :)

**Comment by seevik2580** [comment]
new PR merged #12 
now every single proxy you create with tor ipchanger has its own dynamic password for controlPort, not static one like in version 1.2.3
linux version 1.2.4 coming soon

**Comment by chrisovato** [comment]
Could you write code for telnet tor to change IP once? It will look like this? 
```
tn = telnetlib.Telnet('127.0.0.1', '10500', 5) tn.write(b"signal NEWNYM\r\n")
```
Again could you link all available commands that I can send through telnet to tor? 
Whats changed when you created for every single proxy new hashed password? I know that it is more secure but something else?

**Comment by seevik2580** [comment]
- no
- no
- yes its only more secure, nothing more
- yes, dunno, maybe middle proxy attacks ? use your imagination.

in a nutshell:
sorry but i dont have time for this ... i asked you to ask questions only about tor ip changer. and you repeatedly ask questions about other stuffs .. so im closing this issue. feel free to ask about tor ipchanger anytime but nothing else. if you have question about anything else
 then [google.com](https://google.com)

if you dont know how to code with python then go learn it first
if you dont know how to use telnet with python then go learn it first
if you dont know how tor.exe works then go learn it first

i had to did all steps by myself. so if i can learn it, anybody else do too
i am not developer nor maintainer tor network or tor.exe client. ask developers how it works.

**Comment by chrisovato** [comment]
OK thanks for your help, in the future I will ask questions only associated with your apps 👨‍💻

**Comment by seevik2580** [comment]
feel free to ask anything about tor ipchanger anytime :)
