### ISSUE TITLE
Question about ipchanger

### ISSUE THREAD

**Issue by chrisovato** [seevik2580/tor-ip-changer#14]
1) What is [tail.exe](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L52)? Why ipchanger need it?

**Comment by seevik2580** [comment]
[tail.exe](https://man7.org/linux/man-pages/man1/tail.1.html) is a windows terminal based version of linux tool to see text files inside terminal, if you click on Logs and select Show debug console, thats what tail.exe does. it shows you live output of log files.

**Comment by chrisovato** [comment]
Where in the code I can turn off silent mode of tor.exe? I want to debug, but flag -d it is not enough for me.

**Comment by seevik2580** [comment]
change `tor.exe -log notice` to `tor.exe -log debug`

**Comment by seevik2580** [comment]
change `tor.exe --log notice` to `tor.exe --log debug` in cca 6 places in code
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L697)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L700)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L725)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L727)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L748)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L750)

but if you do that, tor ip changer wont check if tor.exe started ok because its hundreds of lines of text he needs to go through and check if tor.exe started with 100%.. which is not mentioned nowhere if you use --log debug. thats why i used --log notice

**Comment by seevik2580** [comment]
change `tor.exe --log notice` to `tor.exe --log debug` in cca 6 places in code
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L697)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L700)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L725)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L727)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L748)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L750)

but if you do that, tor ip changer wont check if tor.exe started ok because its hundreds of lines of text he needs to go through and check if tor.exe started with 100%.. which is not mentioned nowhere if you use --log debug. thats why i used --log notice
so you will be unable to start Tor server with ipchanger.

**Comment by seevik2580** [comment]
change `tor.exe --log notice` to `tor.exe --log debug` in cca 6 places in code
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L697)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L700)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L725)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L727)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L748)
[here](https://github.com/seevik2580/tor-ip-changer/blob/b87203309eab5dd31ecaf800541cc68d0abb3100/source-code-win/1.2.4/start.pyw#L750)

but if you do that, tor ip changer wont check if tor.exe started ok because its hundreds of lines of text he needs to go through and check if tor.exe started with 100%.. thats why i used --log notice
so you will be unable to start Tor server with ipchanger.

**Comment by chrisovato** [comment]
Which function is checking for these hundreds of lines? I will modify it

**Comment by seevik2580** [comment]
it starts tor.exe with custom options and save logs to file and then it goes through that file to check if tor started ok.

**Comment by seevik2580** [comment]
i found a better solution how to check tor status without go through a large log file. soon in version 1.2.5 :)

**Comment by chrisovato** [comment]
Could you explain what it will be?

**Comment by seevik2580** [comment]
sure, i found that site you wanted from me before, with tor info which commands you can send him by telnet [Here](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt), so you can check tor status with connecting to controlport by telnet and send command `GETINFO status/bootstrap-phase` and also `GETINFO status/circuit-established`,

**Comment by chrisovato** [comment]
Or you can copy all text from file where tor saved it and paste it in your debug console.

**Comment by seevik2580** [comment]
no no i only changed function to check tor status. not logging to files itself. tor will continue to log all his status to log file, but checking status will be through controlport.

**Comment by chrisovato** [comment]
Yes but your function already save logs to file and then it goes through that file to check if tor started ok.
So you can put the content of the file to console when someone run ipchanger.exe with flag -d

**Comment by seevik2580** [comment]
yes i understand and it will be that way, dont worry.

**Comment by chrisovato** [comment]
Can I lookup this file where tor.exe saved all logs? Is it saved in dist folder?

**Comment by seevik2580** [comment]
**Logs** directory

**Comment by seevik2580** [comment]
#15 version 1.2.5 for windows has been released

**Comment by chrisovato** [comment]
How does [that ](https://github.com/seevik2580/tor-ip-changer/blob/f3e99a54a975c4b6f7c0fb8b85dc98d3780f9a91/source-code-win/1.2.5/start.pyw#L930) function work?
I know that it is used to download the missing files, but how it works?

**Comment by seevik2580** [comment]
it uses urllib3 python module to open url, then it converts the url content to bytes, then it will identify total file size. then it starts to download those bytes into chunks of 9192 bytes until total file size is reached. finally it saves all downloaded chunks into one desired file name :)

i used chunk method because then python does not have to wait until one file is downloaded and can do other operations in background such as editing UI elements like the red progress bar based by downloaded % of file on top there. so i can calculate  how many chunks i have downloaded yet and make it visible in UI

![image](https://user-images.githubusercontent.com/22060747/87320907-d7064780-c52b-11ea-9fa3-7eccd47cdefb.png)

**Comment by chrisovato** [comment]
So, for example, it goes [here](https://github.com/seevik2580/tor-ip-changer/blob/master/tor/tor.exe) and check the size of the file ![image](https://user-images.githubusercontent.com/41999914/87323553-37e34f00-c52f-11ea-87e7-e253c82e52f1.png)

And then download chunks made of 9192 bytes. 
How is that working? I can only download whole file, how your app is working that it can download file by chunks? 
9192 is a random number?

**Comment by seevik2580** [comment]
simple, for every request you send to http or https address you get a head response, in this head are informations such as format of content, size of content, and response code (200,404,500 etc) so for tor.exe its exactly [this link](https://raw.githubusercontent.com/seevik2580/tor-ip-changer/master/tor/tor.exe) and header response with size of content is `Content-Length: 3409408`.. if you take that number and divide it with 1024 (convert bytes to kilobytes) youll get `3329,5KB` .. and because windows doesnt know decimals it rounds that size to `3330KB` .. then if you try to use `os.stat("tor.exe").st_size` with python script it returns `3409408` bytes as well and if you look in windows folder to file tor.exe size you see also `3330KB` :)

for small files, you can use simple method to download file with python urllib3 module
```
 import urllib3
 url = 'http://url_to_a_file'
 http= urllib3.PoolManager()
 r = http.request('GET',url )
 f = open(filename, 'wb')
 f.write(resp.data)
 f.close()
 r.release_conn()
```
but its not good for bigger files, because it waits whole time until file is downloaded and then it writes downloaded data into file at once.. so you cant do any other operations in this actual thread. so its better to use chunk method where data are written into file by stream of bytes from buffer.

```
import urllib3
url = 'http://url_to_a_file'
http = urllib3.PoolManager()
r = http.request('GET', url, preload_content=False)

with open(path, 'wb') as out:
    while True:
        data = r.read(chunk_size)
        if not data:
            break
        out.write(data)

r.release_conn()
```
chunk size is up to you (i prefer 8192), well here is 9192 because i write it wrong. but it absolutely doesn't matter, it only determines how big a package of bytes can hold in buffer, then it writes that content of buffer into file and clean buffer.. and again.. it waits for chunk in buffer, then write buffer into file then clean buffer... and again until full file size is reached.

**Comment by odaiasd** [comment]
when i choose palestine (ps) country  its stuck on (45% :  Asking for relay descriptors )
can you help me to fix it ?
Thank you

**Comment by seevik2580** [comment]
> when i choose palestine (ps) country its stuck on (45% : Asking for relay descriptors )
> can you help me to fix it ?
> Thank you

solution here #25
