### ISSUE TITLE
I don't know how to use it with Mac OS can u write documentation for it

### ISSUE THREAD

**Issue by KentelDevelopment** [seevik2580/tor-ip-changer#53]
I need to use it on Mac pls help me

**Comment by seevik2580** [comment]
sadly ipchanger for mac OS is discontinued because i dont have mac OS.
it was just experimental build ... for alternative you can try to use docker version
mentioned here https://github.com/seevik2580/tor-ip-changer/issues/49

download Dockerfile: https://github.com/seevik2580/tor-ip-changer/blob/master/Dockerfile
```
docker build -t . ipchanger
xhost +
docker run -p 14999:14999 -p 9050:9050 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ipchanger
```
or download Docker-compose: https://github.com/seevik2580/tor-ip-changer/blob/master/docker-compose.yml
```
xhost +
docker-compose up -d
```
