### ISSUE TITLE
Only 6000 nodes

### ISSUE THREAD

**Issue by chrisooo3** [seevik2580/tor-ip-changer#54]
Hi, 
with tor network I can have only about 6000 different IP addresses.

I have found something like [smartproxy](https://smartproxy.com/)  which offers over 40M ip addresses. 

Do you know how it is possible that they have that amount of IP addresses? 
I have been emailing them about that if they have physically 40M+ machines that they can use and they did not answer me.

Maybe you will know it.

**Comment by seevik2580** [comment]
Hi,
my opinion is that Tor can lead you to deep/dark web which is not accessible by normal browsers or normal proxies. And smartproxy only work with surface web. So its understandable that Tor has limited number of ips to minimize impact because dark/deep web is really full of horrible things and you dont want to have this accessible from 40M ips which can lead to that everyone can browse that. Smaller pack of ips have better control and monitoring options.

![image](https://user-images.githubusercontent.com/22060747/132098698-da4747fd-5b0c-4506-a2f3-b6153dc4baee.png)

but its just an opinion.. i have no clue
