### ISSUE TITLE
Why always stuck in 5%

### ISSUE THREAD

**Issue by Roywaller** [seevik2580/tor-ip-changer#6]
I tried these two way, but doesn't work. It's always stuck in 5%: Connecting to directory server 
`Problem connecting to this node try to change country 
or delete all tordata folders inside Data folder`

**Comment by seevik2580** [comment]
send me both log files tor_your_date_time.txt and ipchanger_your_date_time.log

**Comment by Roywaller** [comment]
I'm in china, and the ISP is blocked, but when I use bridges the Tor Browser it's work. Thanks a lot for help!
[ipchanger_2018_05_21_11_46_45.log](https://github.com/seevik2580/tor-ip-changer/files/2021161/ipchanger_2018_05_21_11_46_45.log)
[tor_2018_05_21_11_46_45.txt](https://github.com/seevik2580/tor-ip-changer/files/2021162/tor_2018_05_21_11_46_45.txt)

**Comment by seevik2580** [comment]
thanks for the logs.. but if your ISP blocks TOR network you can also use bridges with TOR IP changer which is supported from version 1.2.1, you are using version 1.2.2 so that should be fine.
go to Options > Settings .. and select Use bridges: YES.
then it connect through bridges listed in folder Tor/bridges.txt, and it should work. you can also use your own bridges, just type them into file bridges.txt inside folder Tor :)
